---
- name: Bash - Check if already setup
  ansible.builtin.stat:
    path: ~/.myconfig/bash
  register: role_bash_state

- name: Debug
  ansible.builtin.debug:
    msg: "{{ role_bash_state }}"

- name: Bash [1/3] - Create bashrc plugin folder
  ansible.builtin.file:
    path: ~/.bashrc.d
    state: directory
  when: role_bash_state.stat.exists is false

- name: Bash [2/3] - Add config to .bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    create: true
    state: present
    append_newline: true
    prepend_newline: true
    block: |
      # myconfig - bashrc customisations
      for file in ~/.bashrc.d/*.bashrc; do
        source "$file"
      done
  when:
    - ansible_os_family == "Debian"
    - role_bash_state.stat.exists is false

- name: Bash [3/3] - Copy bashrc plugins
  ansible.builtin.copy:
    src: files/
    dest: ~/.bashrc.d/
  when: role_bash_state.stat.exists is false

- name: Bash - Finalising
  ansible.builtin.file:
    path: ~/.myconfig/bash
    state: touch
  when: role_bash_state.stat.exists is false
