---
- name: feh [1/3] - Install (Debian)
  ansible.builtin.apt:
    name: feh
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: feh [1/3] - Install (RedHat)
  ansible.builtin.dnf:
    name: feh
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "RedHat"

- name: feh [2/3] - Ensure required paths exist
  ansible.builtin.file:
    path: ~/Pictures/wallpapers
    state: directory

- name: feh [3/3] - [Optional] Add default background
  ansible.builtin.copy:
    src: /usr/share/background/gnome/adwaita-d.webp
    dest: ~/Pictures/wallpapers/
    mode: "0644"
  ignore_errors: true
