---
- name: Update software cache and upgrade OS (Debian)
  ansible.builtin.apt:
    name: "*"
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Update software cache and upgrade OS (RedHat)
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Configure terminal
  ansible.builtin.include_role:
    name: linux-terminal

- name: Configure desktop environment
  ansible.builtin.include_role:
    name: linux-ui
